version: '3.7'

services:

  eventstore:
    container_name: esdb-docs
    #image: eventstore/eventstore:release-5.0.10
    image: eventstore/eventstore:latest
    ports:
      - '2113:2113'
      - '1112:1112'
      - '1113:1113'
    environment:
      EVENTSTORE_EXT_TCP_PORT: 1113
      #EVENTSTORE_EXT_HTTP_PORT: 2113
      EVENTSTORE_RUN_PROJECTIONS: all
      EVENTSTORE_START_STANDARD_PROJECTIONS: 'true'
      PROJECTION_THREADS: 8
      INSECURE: true
      EVENTSTORE_INSECURE: true
      #EVENTSTORE_CLUSTER_SIZE: 1
      #EVENTSTORE_DISCOVER_VIA_DNS: false
      EVENTSTORE_ENABLE_EXTERNAL_TCP: true
      EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: true
      #EVENTSTORE_ADVERTISE_HOST_TO_CLIENT_AS: 127.0.0.1

    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

volumes:
  eventstore-volume-data:
  eventstore-volume-logs: